### ISSUE TITLE
TypeError: Cannot set property 'inline' of undefined

### ISSUE THREAD

**Issue by SkyzohKey** [jonschlinkert/remarkable#172]
```bash
/home/skyzohkey/Dev/NodeJS/SkyzohKey-Devblog/node_modules/remarkable/lib/index.js:59
  this.inline   = new ParserInline();
                ^
TypeError: Cannot set property 'inline' of undefined
    at Remarkable (/home/skyzohkey/Dev/NodeJS/SkyzohKey-Devblog/node_modules/remarkable/lib/index.js:59:17)
    at Object.<anonymous> (/home/skyzohkey/Dev/NodeJS/SkyzohKey-Devblog/app.js:14:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/skyzohkey/Dev/NodeJS/SkyzohKey-Devblog/bin/www:7:11)
    at Module._compile (module.js:456:26)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by SkyzohKey** [comment]
Fixed by checking if the object is an instance of itself : 

`remarkable/lib/index.js:53`
```js
function Remarkable(preset, options) {
  if (!(this instanceof Remarkable)) {
    return new Remarkable(preset, options);
  }

  if (typeof preset !== 'string') {
    options = preset;
    preset = 'default';
  }

  this.inline   = new ParserInline();
  this.block    = new ParserBlock();
  this.core     = new ParserCore();
  this.renderer = new Renderer();
  this.ruler    = new Ruler();

  this.options  = {};
  this.configure(config[preset]);
  this.set(options || {});
}
```
