### ISSUE TITLE
Not compiling and installing on current Ubuntu 16.04 beta 

### ISSUE THREAD

**Issue by SirSharpest** [jonschlinkert/remarkable#202]
Fresh installs of the latest Ubuntu 16.04 beta are allowing install, getting this output when running from terminal: 

```
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 48, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3/dist-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 86, in add_from_file
    Gtk.Builder.add_from_file(self, filename)
GLib.Error: gtk-builder-error-quark: /usr/share/remarkable/ui/RemarkableWindow.ui:835:58 Object with ID  not found (13)
```

**Comment by doowb** [comment]
@SirSharpest looks like you're looking for the remarkable editor. These issues are for the remarkable markdown parser.
