### ISSUE TITLE
dep fails (styles, findBar) & 'TypeError: 'module' object is not callable' on OpenSUSE install 

### ISSUE THREAD

**Issue by pgnd** [jonschlinkert/remarkable#289]
1st install of Remarkable/head on OpenSUSE 42.3,

```
git log | head
	commit da0d88c0a6e3f6e3d61c68ed47aa65f8ab880397
	Author: Jamie McGowan <jamiemcgowan.dev@gmail.com>
	Date:   Sat Jan 6 00:21:20 2018 +0000

	    Fix: Hide findbar properly when escape key is pressed. Still problem: matched text remains highlighted after findbar is hidden

	commit 31ab4abade78b9313ee6179ba39ca76960d52696
	Author: Jamie McGowan <jamiemcgowan.dev@gmail.com>
	Date:   Sat Jan 6 00:03:02 2018 +0000
```

seeing a bunch of dependency fails; 'fixing' them one at a time,

exec
```
./bin/remarkable
	Traceback (most recent call last):
	  File "./bin/remarkable", line 65, in <module>
	    import remarkable
	  File "/usr/local/src/Remarkable/remarkable/__init__.py", line 30, in <module>
	    from remarkable import RemarkableWindow
	  File "/usr/local/src/Remarkable/remarkable/RemarkableWindow.py", line 39, in <module>
	    import styles
	ImportError: No module named 'styles'
```

mod
```
perl -pi -e '\
 s|^(import styles)|from remarkable ${1}|g' \
./remarkable/RemarkableWindow.py
./bin/remarkable
	Traceback (most recent call last):
	  File "./bin/remarkable", line 65, in <module>
	    import remarkable
	  File "/usr/local/src/Remarkable/remarkable/__init__.py", line 30, in <module>
	    from remarkable import RemarkableWindow
	  File "/usr/local/src/Remarkable/remarkable/RemarkableWindow.py", line 43, in <module>
	    from findBar import FindBar
	ImportError: No module named 'findBar'
```

mod
```
perl -pi -e '\
 s|^(from )findBar( import FindBar)|${1}remarkable${2}|g' \
./remarkable/RemarkableWindow.py
./bin/remarkable
	Traceback (most recent call last):
	  File "./bin/remarkable", line 65, in <module>
	    import remarkable
	  File "/usr/local/src/Remarkable/remarkable/__init__.py", line 30, in <module>
	    from remarkable import RemarkableWindow
	  File "/usr/local/src/Remarkable/remarkable/RemarkableWindow.py", line 43, in <module>
	    from remarkable import FindBar
	ImportError: cannot import name 'FindBar'
```

mod
```
cd remarkable/
ln -sf findBar.py FindBar.py
cd ../
./bin/remarkable
	openjdk version "1.8.0_151"
	OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-281.2-x86_64)
	OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
	Traceback (most recent call last):
	  File "./bin/remarkable", line 66, in <module>
	    remarkable.main()
	  File "/usr/local/src/Remarkable/remarkable/__init__.py", line 49, in main
	    window = RemarkableWindow.RemarkableWindow()
	  File "/usr/local/src/Remarkable/remarkable_lib/Window.py", line 54, in __new__
	    new_object.finish_initializing(builder)
	  File "/usr/local/src/Remarkable/remarkable/RemarkableWindow.py", line 154, in finish_initializing
	    match_case, whole_word, regex)
	TypeError: 'module' object is not callable
```

possible I've turned down the wrong rabbit hole here ...

**Comment by doowb** [comment]
Wrong repository. It looks like you found the correct one and opened an issue there.

**Comment by pgnd** [comment]
ugh, sry.  didn't even notice the difference!  wondered where this $&^$&% post went ...
